### ISSUE TITLE
All white screen after update to 2.2.0

### ISSUE THREAD

**Issue by pjmsullivan** [euphy/polargraph_server_polarshield_esp32#8]
After update to v2.2.0 with precompiled binaries, the screen remains all white and never displays the Polargraph logo or anything.  Reverted back to 2.1.5 and everything works appropriately, as expected.  I tried downloading the new firmware twice to ensure there was no corrupt file when uploading to esp32.  Anyway, I'm just happy you created this great software!  I just thought I'd ping you if anyone else might have this issue.

Thanks again, Sandy!

**Comment by euphy** [comment]
Thanks for the report - I hadn't tested it myself and looks like I messed up the bootloader files somehow. Fixed for me anyway, will you have a try and close the issue if you think it's fixed?

**Comment by pjmsullivan** [comment]
Worked like a charm!  Thanks again!
